# **Indexing and Slicing**

In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:]
#returns all elements from the index position 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[0:10]
#doesn't inclue 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[-1]
#last element of the array

10

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
array=np.arange(0,10)

In [17]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
array[:]
#returns all elements

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
slice_arr = array[0:5]

In [25]:
slice_arr[:] = 20

In [26]:
slice_arr

array([20, 20, 20, 20, 20])

In [28]:
array

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9])

In [29]:
#copying one array on to another
arr_copy = array.copy()

In [31]:
array

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9])

In [32]:
arr_copy

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9])

In [34]:
array == arr_copy

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [35]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [36]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [40]:
print(arr_2d[0,0]) #or
print(arr_2d[0][0])
#gives the same output --> 10

10
10


In [41]:
#to get 60
arr_2d[1][2]

60

In [42]:
#to get 80
arr_2d[2,1]

80

In [46]:
#to get 20, 30, 50, 60
arr_2d[:2, 1:]

array([[20, 30],
       [50, 60]])

In [48]:
#to get 20, 50, 80 vertically
arr_2d[:3, 1:2]

array([[20],
       [50],
       [80]])

In [50]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [58]:
#to get 40, 70
arr_2d[1:3, 0]

array([40, 70])

In [61]:
#to get 50, 60, 80, 90
arr_2d[1:3, 1:]

array([[50, 60],
       [80, 90]])

In [62]:
arr_2d = np.zeros((10, 10))

In [63]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
arr_len = arr_2d.shape[1]

In [65]:
for i in range(arr_len):
    arr_2d[i] = i

In [66]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [67]:
arr_2d[[2, 4, 6, 8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [68]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [69]:
arr_2d[[6, 2, 7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [70]:
arr = np.arange(1,11)

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [74]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])