# **Operations**

In [1]:
import numpy as np

In [8]:
arr1 = np.arange(1,11)

In [11]:
arr2 = np.arange(1,21,2)

In [14]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [16]:
sq_arr1 = arr1 ** 2

In [17]:
sq_arr1

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [18]:
mul_arr = arr1 * arr2

In [19]:
mul_arr

array([  1,   6,  15,  28,  45,  66,  91, 120, 153, 190])

In [6]:
sub_arr = arr - arr

In [7]:
sub_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
arr_add = arr1 + arr2

In [21]:
arr_add

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [24]:
arr1/arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
arr1/0

C:\Users\srinija\.conda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [26]:
1/arr1

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [28]:
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [30]:
np.exp(arr1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [31]:
np.max(arr1)

10

In [32]:
np.min(arr2)

1

In [33]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [34]:
np.log(arr2)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])